// Generated by scripts/build-unit1.py from the supplied Unit 1 list.
export const verbs = [
  {
    "infinitive": "ser",
    "base": "ser",
    "meaning": "to be",
    "type": "irregular",
    "reflexive": false,
    "stemChanging": false,
    "explanation": "Irregular present tense: soy, eres, es, somos, sois, son.",
    "forms": [
      "soy",
      "eres",
      "es",
      "somos",
      "sois",
      "son"
    ]
  },
  {
    "infinitive": "estar",
    "base": "estar",
    "meaning": "to be",
    "type": "irregular",
    "reflexive": false,
    "stemChanging": false,
    "explanation": "Irregular present tense: estoy, estás, está, estamos, estáis, están.",
    "forms": [
      "estoy",
      "estás",
      "está",
      "estamos",
      "estáis",
      "están"
    ]
  },
  {
    "infinitive": "tener",
    "base": "tener",
    "meaning": "to have",
    "type": "irregular",
    "reflexive": false,
    "stemChanging": true,
    "explanation": "Irregular present tense: tengo, tienes, tiene, tenemos, tenéis, tienen. Yo uses tengo; tú, él/ella/usted, and ellos/ellas/ustedes also change e → ie.",
    "forms": [
      "tengo",
      "tienes",
      "tiene",
      "tenemos",
      "tenéis",
      "tienen"
    ]
  },
  {
    "infinitive": "ir",
    "base": "ir",
    "meaning": "to go",
    "type": "irregular",
    "reflexive": false,
    "stemChanging": false,
    "explanation": "Irregular present tense: voy, vas, va, vamos, vais, van.",
    "forms": [
      "voy",
      "vas",
      "va",
      "vamos",
      "vais",
      "van"
    ]
  },
  {
    "infinitive": "hacer",
    "base": "hacer",
    "meaning": "to do / to make",
    "type": "irregular",
    "reflexive": false,
    "stemChanging": false,
    "explanation": "Irregular present tense: hago, haces, hace, hacemos, hacéis, hacen.",
    "forms": [
      "hago",
      "haces",
      "hace",
      "hacemos",
      "hacéis",
      "hacen"
    ]
  },
  {
    "infinitive": "querer",
    "base": "querer",
    "meaning": "to want",
    "type": "stem",
    "reflexive": false,
    "stemChanging": true,
    "explanation": "e → ie in the stressed stem. Nosotros and vosotros keep quer-.",
    "forms": [
      "quiero",
      "quieres",
      "quiere",
      "queremos",
      "queréis",
      "quieren"
    ]
  },
  {
    "infinitive": "poder",
    "base": "poder",
    "meaning": "can / to be able to",
    "type": "stem",
    "reflexive": false,
    "stemChanging": true,
    "explanation": "o → ue in the stressed stem. Nosotros and vosotros keep pod-.",
    "forms": [
      "puedo",
      "puedes",
      "puede",
      "podemos",
      "podéis",
      "pueden"
    ]
  },
  {
    "infinitive": "gustar (one thing)",
    "base": "gustar",
    "meaning": "to like",
    "type": "special",
    "reflexive": false,
    "forms": [
      "me gusta",
      "te gusta",
      "le gusta",
      "nos gusta",
      "os gusta",
      "les gusta"
    ],
    "subjects": [
      "a mí · el libro",
      "a ti · el libro",
      "a él / a ella / a usted · el libro",
      "a nosotros / a nosotras · el libro",
      "a vosotros / a vosotras · el libro",
      "a ellos / a ellas / a ustedes · el libro"
    ],
    "explanation": "The thing liked is the grammatical subject: gusta for one thing or an infinitive, gustan for plural things. Use me, te, le, nos, os, or les for the person who likes it. Enter the pronoun and verb only."
  },
  {
    "infinitive": "gustar (plural things)",
    "base": "gustar",
    "meaning": "to like",
    "type": "special",
    "reflexive": false,
    "forms": [
      "me gustan",
      "te gustan",
      "le gustan",
      "nos gustan",
      "os gustan",
      "les gustan"
    ],
    "subjects": [
      "a mí · los libros",
      "a ti · los libros",
      "a él / a ella / a usted · los libros",
      "a nosotros / a nosotras · los libros",
      "a vosotros / a vosotras · los libros",
      "a ellos / a ellas / a ustedes · los libros"
    ],
    "explanation": "The thing liked is the grammatical subject: gusta for one thing or an infinitive, gustan for plural things. Use me, te, le, nos, os, or les for the person who likes it. Enter the pronoun and verb only."
  },
  {
    "infinitive": "necesitar",
    "base": "necesitar",
    "meaning": "to need",
    "type": "regular",
    "reflexive": false,
    "stemChanging": false,
    "explanation": "Regular -ar present-tense endings.",
    "forms": [
      "necesito",
      "necesitas",
      "necesita",
      "necesitamos",
      "necesitáis",
      "necesitan"
    ]
  },
  {
    "infinitive": "saber",
    "base": "saber",
    "meaning": "to know",
    "type": "irregular",
    "reflexive": false,
    "stemChanging": false,
    "explanation": "Irregular present tense: sé, sabes, sabe, sabemos, sabéis, saben.",
    "forms": [
      "sé",
      "sabes",
      "sabe",
      "sabemos",
      "sabéis",
      "saben"
    ]
  },
  {
    "infinitive": "hablar",
    "base": "hablar",
    "meaning": "to speak",
    "type": "regular",
    "reflexive": false,
    "stemChanging": false,
    "explanation": "Regular -ar present-tense endings.",
    "forms": [
      "hablo",
      "hablas",
      "habla",
      "hablamos",
      "habláis",
      "hablan"
    ]
  },
  {
    "infinitive": "escuchar",
    "base": "escuchar",
    "meaning": "to listen",
    "type": "regular",
    "reflexive": false,
    "stemChanging": false,
    "explanation": "Regular -ar present-tense endings.",
    "forms": [
      "escucho",
      "escuchas",
      "escucha",
      "escuchamos",
      "escucháis",
      "escuchan"
    ]
  },
  {
    "infinitive": "mirar",
    "base": "mirar",
    "meaning": "to watch / to look at",
    "type": "regular",
    "reflexive": false,
    "stemChanging": false,
    "explanation": "Regular -ar present-tense endings.",
    "forms": [
      "miro",
      "miras",
      "mira",
      "miramos",
      "miráis",
      "miran"
    ]
  },
  {
    "infinitive": "ver",
    "base": "ver",
    "meaning": "to watch / to look at",
    "type": "irregular",
    "reflexive": false,
    "stemChanging": false,
    "explanation": "Irregular present tense: veo, ves, ve, vemos, veis, ven.",
    "forms": [
      "veo",
      "ves",
      "ve",
      "vemos",
      "veis",
      "ven"
    ]
  },
  {
    "infinitive": "leer",
    "base": "leer",
    "meaning": "to read",
    "type": "regular",
    "reflexive": false,
    "stemChanging": false,
    "explanation": "Regular -er present-tense endings.",
    "forms": [
      "leo",
      "lees",
      "lee",
      "leemos",
      "leéis",
      "leen"
    ]
  },
  {
    "infinitive": "escribir",
    "base": "escribir",
    "meaning": "to write",
    "type": "regular",
    "reflexive": false,
    "stemChanging": false,
    "explanation": "Regular -ir present-tense endings.",
    "forms": [
      "escribo",
      "escribes",
      "escribe",
      "escribimos",
      "escribís",
      "escriben"
    ]
  },
  {
    "infinitive": "estudiar",
    "base": "estudiar",
    "meaning": "to study",
    "type": "regular",
    "reflexive": false,
    "stemChanging": false,
    "explanation": "Regular -ar present-tense endings.",
    "forms": [
      "estudio",
      "estudias",
      "estudia",
      "estudiamos",
      "estudiáis",
      "estudian"
    ]
  },
  {
    "infinitive": "trabajar",
    "base": "trabajar",
    "meaning": "to work",
    "type": "regular",
    "reflexive": false,
    "stemChanging": false,
    "explanation": "Regular -ar present-tense endings.",
    "forms": [
      "trabajo",
      "trabajas",
      "trabaja",
      "trabajamos",
      "trabajáis",
      "trabajan"
    ]
  },
  {
    "infinitive": "comer",
    "base": "comer",
    "meaning": "to eat",
    "type": "regular",
    "reflexive": false,
    "stemChanging": false,
    "explanation": "Regular -er present-tense endings.",
    "forms": [
      "como",
      "comes",
      "come",
      "comemos",
      "coméis",
      "comen"
    ]
  },
  {
    "infinitive": "beber",
    "base": "beber",
    "meaning": "to drink",
    "type": "regular",
    "reflexive": false,
    "stemChanging": false,
    "explanation": "Regular -er present-tense endings.",
    "forms": [
      "bebo",
      "bebes",
      "bebe",
      "bebemos",
      "bebéis",
      "beben"
    ]
  },
  {
    "infinitive": "participar",
    "base": "participar",
    "meaning": "to participate",
    "type": "regular",
    "reflexive": false,
    "stemChanging": false,
    "explanation": "Regular -ar present-tense endings.",
    "forms": [
      "participo",
      "participas",
      "participa",
      "participamos",
      "participáis",
      "participan"
    ]
  },
  {
    "infinitive": "vivir",
    "base": "vivir",
    "meaning": "to live",
    "type": "regular",
    "reflexive": false,
    "stemChanging": false,
    "explanation": "Regular -ir present-tense endings.",
    "forms": [
      "vivo",
      "vives",
      "vive",
      "vivimos",
      "vivís",
      "viven"
    ]
  },
  {
    "infinitive": "jugar",
    "base": "jugar",
    "meaning": "to play",
    "type": "stem",
    "reflexive": false,
    "stemChanging": true,
    "explanation": "u → ue in the stressed stem. Nosotros and vosotros keep jug-.",
    "forms": [
      "juego",
      "juegas",
      "juega",
      "jugamos",
      "jugáis",
      "juegan"
    ]
  },
  {
    "infinitive": "practicar",
    "base": "practicar",
    "meaning": "to practice",
    "type": "regular",
    "reflexive": false,
    "stemChanging": false,
    "explanation": "Regular -ar present-tense endings.",
    "forms": [
      "practico",
      "practicas",
      "practica",
      "practicamos",
      "practicáis",
      "practican"
    ]
  },
  {
    "infinitive": "usar",
    "base": "usar",
    "meaning": "to use",
    "type": "regular",
    "reflexive": false,
    "stemChanging": false,
    "explanation": "Regular -ar present-tense endings.",
    "forms": [
      "uso",
      "usas",
      "usa",
      "usamos",
      "usáis",
      "usan"
    ]
  },
  {
    "infinitive": "visitar",
    "base": "visitar",
    "meaning": "to visit",
    "type": "regular",
    "reflexive": false,
    "stemChanging": false,
    "explanation": "Regular -ar present-tense endings.",
    "forms": [
      "visito",
      "visitas",
      "visita",
      "visitamos",
      "visitáis",
      "visitan"
    ]
  },
  {
    "infinitive": "pasar",
    "base": "pasar",
    "meaning": "to spend / to pass",
    "type": "regular",
    "reflexive": false,
    "stemChanging": false,
    "explanation": "Regular -ar present-tense endings.",
    "forms": [
      "paso",
      "pasas",
      "pasa",
      "pasamos",
      "pasáis",
      "pasan"
    ]
  },
  {
    "infinitive": "correr",
    "base": "correr",
    "meaning": "to run",
    "type": "regular",
    "reflexive": false,
    "stemChanging": false,
    "explanation": "Regular -er present-tense endings.",
    "forms": [
      "corro",
      "corres",
      "corre",
      "corremos",
      "corréis",
      "corren"
    ]
  },
  {
    "infinitive": "caminar",
    "base": "caminar",
    "meaning": "to walk",
    "type": "regular",
    "reflexive": false,
    "stemChanging": false,
    "explanation": "Regular -ar present-tense endings.",
    "forms": [
      "camino",
      "caminas",
      "camina",
      "caminamos",
      "camináis",
      "caminan"
    ]
  },
  {
    "infinitive": "aprender",
    "base": "aprender",
    "meaning": "to learn",
    "type": "regular",
    "reflexive": false,
    "stemChanging": false,
    "explanation": "Regular -er present-tense endings.",
    "forms": [
      "aprendo",
      "aprendes",
      "aprende",
      "aprendemos",
      "aprendéis",
      "aprenden"
    ]
  },
  {
    "infinitive": "comprar",
    "base": "comprar",
    "meaning": "to buy",
    "type": "regular",
    "reflexive": false,
    "stemChanging": false,
    "explanation": "Regular -ar present-tense endings.",
    "forms": [
      "compro",
      "compras",
      "compra",
      "compramos",
      "compráis",
      "compran"
    ]
  },
  {
    "infinitive": "terminar",
    "base": "terminar",
    "meaning": "to finish",
    "type": "regular",
    "reflexive": false,
    "stemChanging": false,
    "explanation": "Regular -ar present-tense endings.",
    "forms": [
      "termino",
      "terminas",
      "termina",
      "terminamos",
      "termináis",
      "terminan"
    ]
  },
  {
    "infinitive": "esperar",
    "base": "esperar",
    "meaning": "to wait",
    "type": "regular",
    "reflexive": false,
    "stemChanging": false,
    "explanation": "Regular -ar present-tense endings.",
    "forms": [
      "espero",
      "esperas",
      "espera",
      "esperamos",
      "esperáis",
      "esperan"
    ]
  },
  {
    "infinitive": "dormir",
    "base": "dormir",
    "meaning": "to sleep",
    "type": "stem",
    "reflexive": false,
    "stemChanging": true,
    "explanation": "o → ue in the stressed stem. Nosotros and vosotros keep dorm-.",
    "forms": [
      "duermo",
      "duermes",
      "duerme",
      "dormimos",
      "dormís",
      "duermen"
    ]
  },
  {
    "infinitive": "preguntar",
    "base": "preguntar",
    "meaning": "to ask",
    "type": "regular",
    "reflexive": false,
    "stemChanging": false,
    "explanation": "Regular -ar present-tense endings.",
    "forms": [
      "pregunto",
      "preguntas",
      "pregunta",
      "preguntamos",
      "preguntáis",
      "preguntan"
    ]
  },
  {
    "infinitive": "pensar",
    "base": "pensar",
    "meaning": "to think",
    "type": "stem",
    "reflexive": false,
    "stemChanging": true,
    "explanation": "e → ie in the stressed stem. Nosotros and vosotros keep pens-.",
    "forms": [
      "pienso",
      "piensas",
      "piensa",
      "pensamos",
      "pensáis",
      "piensan"
    ]
  },
  {
    "infinitive": "empezar",
    "base": "empezar",
    "meaning": "to start",
    "type": "stem",
    "reflexive": false,
    "stemChanging": true,
    "explanation": "e → ie in the stressed stem. Nosotros and vosotros keep empez-.",
    "forms": [
      "empiezo",
      "empiezas",
      "empieza",
      "empezamos",
      "empezáis",
      "empiezan"
    ]
  },
  {
    "infinitive": "comenzar",
    "base": "comenzar",
    "meaning": "to start",
    "type": "stem",
    "reflexive": false,
    "stemChanging": true,
    "explanation": "e → ie in the stressed stem. Nosotros and vosotros keep comenz-.",
    "forms": [
      "comienzo",
      "comienzas",
      "comienza",
      "comenzamos",
      "comenzáis",
      "comienzan"
    ]
  },
  {
    "infinitive": "entender",
    "base": "entender",
    "meaning": "to understand",
    "type": "stem",
    "reflexive": false,
    "stemChanging": true,
    "explanation": "e → ie in the stressed stem. Nosotros and vosotros keep entend-.",
    "forms": [
      "entiendo",
      "entiendes",
      "entiende",
      "entendemos",
      "entendéis",
      "entienden"
    ]
  },
  {
    "infinitive": "comprender",
    "base": "comprender",
    "meaning": "to understand",
    "type": "regular",
    "reflexive": false,
    "stemChanging": false,
    "explanation": "Regular -er present-tense endings.",
    "forms": [
      "comprendo",
      "comprendes",
      "comprende",
      "comprendemos",
      "comprendéis",
      "comprenden"
    ]
  },
  {
    "infinitive": "ganar",
    "base": "ganar",
    "meaning": "to win",
    "type": "regular",
    "reflexive": false,
    "stemChanging": false,
    "explanation": "Regular -ar present-tense endings.",
    "forms": [
      "gano",
      "ganas",
      "gana",
      "ganamos",
      "ganáis",
      "ganan"
    ]
  },
  {
    "infinitive": "despertarse",
    "base": "despertar",
    "meaning": "to wake up",
    "type": "stem",
    "reflexive": true,
    "stemChanging": true,
    "explanation": "e → ie in the stressed stem. Nosotros and vosotros keep despert-. Match the reflexive pronoun to the subject: me, te, se, nos, os, se.",
    "forms": [
      "me despierto",
      "te despiertas",
      "se despierta",
      "nos despertamos",
      "os despertáis",
      "se despiertan"
    ]
  },
  {
    "infinitive": "levantarse",
    "base": "levantar",
    "meaning": "to get up",
    "type": "regular",
    "reflexive": true,
    "stemChanging": false,
    "explanation": "Regular -ar present-tense endings. Match the reflexive pronoun to the subject: me, te, se, nos, os, se.",
    "forms": [
      "me levanto",
      "te levantas",
      "se levanta",
      "nos levantamos",
      "os levantáis",
      "se levantan"
    ]
  },
  {
    "infinitive": "acostarse",
    "base": "acostar",
    "meaning": "to go to bed",
    "type": "stem",
    "reflexive": true,
    "stemChanging": true,
    "explanation": "o → ue in the stressed stem. Nosotros and vosotros keep acost-. Match the reflexive pronoun to the subject: me, te, se, nos, os, se.",
    "forms": [
      "me acuesto",
      "te acuestas",
      "se acuesta",
      "nos acostamos",
      "os acostáis",
      "se acuestan"
    ]
  },
  {
    "infinitive": "dormirse",
    "base": "dormir",
    "meaning": "to fall asleep / to go to sleep",
    "type": "stem",
    "reflexive": true,
    "stemChanging": true,
    "explanation": "o → ue in the stressed stem. Nosotros and vosotros keep dorm-. Match the reflexive pronoun to the subject: me, te, se, nos, os, se.",
    "forms": [
      "me duermo",
      "te duermes",
      "se duerme",
      "nos dormimos",
      "os dormís",
      "se duermen"
    ]
  },
  {
    "infinitive": "ducharse",
    "base": "duchar",
    "meaning": "to shower",
    "type": "regular",
    "reflexive": true,
    "stemChanging": false,
    "explanation": "Regular -ar present-tense endings. Match the reflexive pronoun to the subject: me, te, se, nos, os, se.",
    "forms": [
      "me ducho",
      "te duchas",
      "se ducha",
      "nos duchamos",
      "os ducháis",
      "se duchan"
    ]
  },
  {
    "infinitive": "bañarse",
    "base": "bañar",
    "meaning": "to bathe / to take a bath",
    "type": "regular",
    "reflexive": true,
    "stemChanging": false,
    "explanation": "Regular -ar present-tense endings. Match the reflexive pronoun to the subject: me, te, se, nos, os, se.",
    "forms": [
      "me baño",
      "te bañas",
      "se baña",
      "nos bañamos",
      "os bañáis",
      "se bañan"
    ]
  },
  {
    "infinitive": "lavarse la cara",
    "base": "lavar",
    "meaning": "to wash one's face",
    "type": "regular",
    "reflexive": true,
    "stemChanging": false,
    "explanation": "Regular -ar present-tense endings. Match the reflexive pronoun to the subject: me, te, se, nos, os, se. Keep “la cara” after the verb.",
    "forms": [
      "me lavo la cara",
      "te lavas la cara",
      "se lava la cara",
      "nos lavamos la cara",
      "os laváis la cara",
      "se lavan la cara"
    ]
  },
  {
    "infinitive": "lavarse las manos",
    "base": "lavar",
    "meaning": "to wash one's hands",
    "type": "regular",
    "reflexive": true,
    "stemChanging": false,
    "explanation": "Regular -ar present-tense endings. Match the reflexive pronoun to the subject: me, te, se, nos, os, se. Keep “las manos” after the verb.",
    "forms": [
      "me lavo las manos",
      "te lavas las manos",
      "se lava las manos",
      "nos lavamos las manos",
      "os laváis las manos",
      "se lavan las manos"
    ]
  },
  {
    "infinitive": "cepillarse los dientes",
    "base": "cepillar",
    "meaning": "to brush one's teeth",
    "type": "regular",
    "reflexive": true,
    "stemChanging": false,
    "explanation": "Regular -ar present-tense endings. Match the reflexive pronoun to the subject: me, te, se, nos, os, se. Keep “los dientes” after the verb.",
    "forms": [
      "me cepillo los dientes",
      "te cepillas los dientes",
      "se cepilla los dientes",
      "nos cepillamos los dientes",
      "os cepilláis los dientes",
      "se cepillan los dientes"
    ]
  },
  {
    "infinitive": "cepillarse el pelo",
    "base": "cepillar",
    "meaning": "to brush one's hair",
    "type": "regular",
    "reflexive": true,
    "stemChanging": false,
    "explanation": "Regular -ar present-tense endings. Match the reflexive pronoun to the subject: me, te, se, nos, os, se. Keep “el pelo” after the verb.",
    "forms": [
      "me cepillo el pelo",
      "te cepillas el pelo",
      "se cepilla el pelo",
      "nos cepillamos el pelo",
      "os cepilláis el pelo",
      "se cepillan el pelo"
    ]
  },
  {
    "infinitive": "peinarse",
    "base": "peinar",
    "meaning": "to comb one's hair",
    "type": "regular",
    "reflexive": true,
    "stemChanging": false,
    "explanation": "Regular -ar present-tense endings. Match the reflexive pronoun to the subject: me, te, se, nos, os, se.",
    "forms": [
      "me peino",
      "te peinas",
      "se peina",
      "nos peinamos",
      "os peináis",
      "se peinan"
    ]
  },
  {
    "infinitive": "vestirse",
    "base": "vestir",
    "meaning": "to get dressed",
    "type": "stem",
    "reflexive": true,
    "stemChanging": true,
    "explanation": "e → i in the stressed stem. Nosotros and vosotros keep vest-. Match the reflexive pronoun to the subject: me, te, se, nos, os, se.",
    "forms": [
      "me visto",
      "te vistes",
      "se viste",
      "nos vestimos",
      "os vestís",
      "se visten"
    ]
  },
  {
    "infinitive": "ponerse",
    "base": "poner",
    "meaning": "to put on",
    "type": "irregular",
    "reflexive": true,
    "stemChanging": false,
    "explanation": "Irregular present tense: pongo, pones, pone, ponemos, ponéis, ponen. Match the reflexive pronoun to the subject: me, te, se, nos, os, se.",
    "forms": [
      "me pongo",
      "te pones",
      "se pone",
      "nos ponemos",
      "os ponéis",
      "se ponen"
    ]
  },
  {
    "infinitive": "quitarse",
    "base": "quitar",
    "meaning": "to take off",
    "type": "regular",
    "reflexive": true,
    "stemChanging": false,
    "explanation": "Regular -ar present-tense endings. Match the reflexive pronoun to the subject: me, te, se, nos, os, se.",
    "forms": [
      "me quito",
      "te quitas",
      "se quita",
      "nos quitamos",
      "os quitáis",
      "se quitan"
    ]
  },
  {
    "infinitive": "prepararse",
    "base": "preparar",
    "meaning": "to get ready",
    "type": "regular",
    "reflexive": true,
    "stemChanging": false,
    "explanation": "Regular -ar present-tense endings. Match the reflexive pronoun to the subject: me, te, se, nos, os, se.",
    "forms": [
      "me preparo",
      "te preparas",
      "se prepara",
      "nos preparamos",
      "os preparáis",
      "se preparan"
    ]
  },
  {
    "infinitive": "afeitarse",
    "base": "afeitar",
    "meaning": "to shave",
    "type": "regular",
    "reflexive": true,
    "stemChanging": false,
    "explanation": "Regular -ar present-tense endings. Match the reflexive pronoun to the subject: me, te, se, nos, os, se.",
    "forms": [
      "me afeito",
      "te afeitas",
      "se afeita",
      "nos afeitamos",
      "os afeitáis",
      "se afeitan"
    ]
  },
  {
    "infinitive": "maquillarse",
    "base": "maquillar",
    "meaning": "to put on makeup",
    "type": "regular",
    "reflexive": true,
    "stemChanging": false,
    "explanation": "Regular -ar present-tense endings. Match the reflexive pronoun to the subject: me, te, se, nos, os, se.",
    "forms": [
      "me maquillo",
      "te maquillas",
      "se maquilla",
      "nos maquillamos",
      "os maquilláis",
      "se maquillan"
    ]
  },
  {
    "infinitive": "sentirse",
    "base": "sentir",
    "meaning": "to feel",
    "type": "stem",
    "reflexive": true,
    "stemChanging": true,
    "explanation": "e → ie in the stressed stem. Nosotros and vosotros keep sent-. Match the reflexive pronoun to the subject: me, te, se, nos, os, se.",
    "forms": [
      "me siento",
      "te sientes",
      "se siente",
      "nos sentimos",
      "os sentís",
      "se sienten"
    ]
  },
  {
    "infinitive": "quedarse",
    "base": "quedar",
    "meaning": "to stay / to remain",
    "type": "regular",
    "reflexive": true,
    "stemChanging": false,
    "explanation": "Regular -ar present-tense endings. Match the reflexive pronoun to the subject: me, te, se, nos, os, se.",
    "forms": [
      "me quedo",
      "te quedas",
      "se queda",
      "nos quedamos",
      "os quedáis",
      "se quedan"
    ]
  },
  {
    "infinitive": "acordarse",
    "base": "acordar",
    "meaning": "to remember",
    "type": "stem",
    "reflexive": true,
    "stemChanging": true,
    "explanation": "o → ue in the stressed stem. Nosotros and vosotros keep acord-. Match the reflexive pronoun to the subject: me, te, se, nos, os, se.",
    "forms": [
      "me acuerdo",
      "te acuerdas",
      "se acuerda",
      "nos acordamos",
      "os acordáis",
      "se acuerdan"
    ]
  },
  {
    "infinitive": "desayunar",
    "base": "desayunar",
    "meaning": "to have breakfast",
    "type": "regular",
    "reflexive": false,
    "stemChanging": false,
    "explanation": "Regular -ar present-tense endings.",
    "forms": [
      "desayuno",
      "desayunas",
      "desayuna",
      "desayunamos",
      "desayunáis",
      "desayunan"
    ]
  },
  {
    "infinitive": "almorzar",
    "base": "almorzar",
    "meaning": "to have lunch",
    "type": "stem",
    "reflexive": false,
    "stemChanging": true,
    "explanation": "o → ue in the stressed stem. Nosotros and vosotros keep almorz-.",
    "forms": [
      "almuerzo",
      "almuerzas",
      "almuerza",
      "almorzamos",
      "almorzáis",
      "almuerzan"
    ]
  },
  {
    "infinitive": "cenar",
    "base": "cenar",
    "meaning": "to have dinner",
    "type": "regular",
    "reflexive": false,
    "stemChanging": false,
    "explanation": "Regular -ar present-tense endings.",
    "forms": [
      "ceno",
      "cenas",
      "cena",
      "cenamos",
      "cenáis",
      "cenan"
    ]
  },
  {
    "infinitive": "llegar",
    "base": "llegar",
    "meaning": "to arrive",
    "type": "regular",
    "reflexive": false,
    "stemChanging": false,
    "explanation": "Regular -ar present-tense endings.",
    "forms": [
      "llego",
      "llegas",
      "llega",
      "llegamos",
      "llegáis",
      "llegan"
    ]
  },
  {
    "infinitive": "salir",
    "base": "salir",
    "meaning": "to leave / to go out",
    "type": "irregular",
    "reflexive": false,
    "stemChanging": false,
    "explanation": "Irregular present tense: salgo, sales, sale, salimos, salís, salen.",
    "forms": [
      "salgo",
      "sales",
      "sale",
      "salimos",
      "salís",
      "salen"
    ]
  },
  {
    "infinitive": "volver",
    "base": "volver",
    "meaning": "to return / to come back",
    "type": "stem",
    "reflexive": false,
    "stemChanging": true,
    "explanation": "o → ue in the stressed stem. Nosotros and vosotros keep volv-.",
    "forms": [
      "vuelvo",
      "vuelves",
      "vuelve",
      "volvemos",
      "volvéis",
      "vuelven"
    ]
  },
  {
    "infinitive": "hacer la tarea",
    "base": "hacer",
    "meaning": "to do homework",
    "type": "irregular",
    "reflexive": false,
    "stemChanging": false,
    "explanation": "Irregular present tense: hago, haces, hace, hacemos, hacéis, hacen. Keep “la tarea” after the verb.",
    "forms": [
      "hago la tarea",
      "haces la tarea",
      "hace la tarea",
      "hacemos la tarea",
      "hacéis la tarea",
      "hacen la tarea"
    ]
  },
  {
    "infinitive": "descansar",
    "base": "descansar",
    "meaning": "to rest",
    "type": "regular",
    "reflexive": false,
    "stemChanging": false,
    "explanation": "Regular -ar present-tense endings.",
    "forms": [
      "descanso",
      "descansas",
      "descansa",
      "descansamos",
      "descansáis",
      "descansan"
    ]
  },
  {
    "infinitive": "limpiar",
    "base": "limpiar",
    "meaning": "to clean",
    "type": "regular",
    "reflexive": false,
    "stemChanging": false,
    "explanation": "Regular -ar present-tense endings.",
    "forms": [
      "limpio",
      "limpias",
      "limpia",
      "limpiamos",
      "limpiáis",
      "limpian"
    ]
  },
  {
    "infinitive": "preparar",
    "base": "preparar",
    "meaning": "to prepare",
    "type": "regular",
    "reflexive": false,
    "stemChanging": false,
    "explanation": "Regular -ar present-tense endings.",
    "forms": [
      "preparo",
      "preparas",
      "prepara",
      "preparamos",
      "preparáis",
      "preparan"
    ]
  }
];
